# Generated by Django 3.0.7 on 2020-07-16 09:58

from django.db import migrations


def create_data(apps, schema_editor):
    User = apps.get_model('Registration', 'User')
    User(first_name="Akash", last_name="Biradar", email="akash@gmail.com", contact_number="9960485557",
         address="Pune").save()
    User(first_name="Pritesh", last_name="Suryawanshi", email="pritesh@gmail.com", contact_number="8830757628",
         address="Pune").save()


class Migration(migrations.Migration):
    dependencies = [
        ('Registration', '0004_user_createdat'),
    ]

    operations = [
    ]
